# Generated by Django 4.1.2 on 2022-10-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_question_model_delete_quesmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question_Model',
            new_name='QuestionModel',
        ),
    ]
