# Generated by Django 4.1.2 on 2022-10-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0008_result_question_alter_result_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, null=True)),
                ('result', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
